[package]
name = "to-do"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
diesel = { version = "2.2.6", features = ["postgres"]}
dotenvy = "0.15"
